services:
  application:
    build:
      context: ./docker-config/php
    container_name: application_api
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx_api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application

  database:
    image: postgres:16
    container_name: postgres_db_api
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: application_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
